# Generated by Django 2.2 on 2019-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=22)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('orthopedics', 'Orthopedics'), ('general_surgery', 'General Surgery'), ('gastroenterologist', 'Gastroenterologist')], max_length=50)),
                ('NID', models.CharField(max_length=14)),
                ('Job_ID', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=8),
        ),
    ]
