# Generated by Django 2.2 on 2019-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_dioxide', models.CharField(max_length=20)),
                ('glucose', models.CharField(max_length=20)),
                ('hormones', models.CharField(max_length=20)),
                ('proteins', models.CharField(max_length=20)),
                ('mineral_salts', models.CharField(max_length=20)),
                ('fats', models.CharField(max_length=20)),
                ('typt', models.CharField(choices=[('A', 'A'), ('O', 'O'), ('B', 'B'), ('B-', 'B-'), ('O-', 'O-'), ('O+', 'O+')], max_length=10)),
            ],
        ),
    ]
