# Generated by Django 2.2 on 2019-04-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('skin_color', models.CharField(choices=[('Very Light', 'Very Light'), ('Normal Light', 'Normal Light'), ('Medium', 'Medium'), ('Light Brown', 'Light Brown'), ('Medium Brown', 'Medium Brown'), ('Brown', 'Brown')], max_length=20)),
            ],
        ),
    ]
