# Generated by Django 2.2 on 2019-04-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_doctor_rate'),
        ('information', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
            ],
        ),
    ]
