# Generated by Django 2.2 on 2019-04-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_doctor_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Doctor')),
            ],
        ),
    ]
