# Generated by Django 2.2 on 2019-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
