# Generated by Django 2.2 on 2019-04-10 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_auto_20190410_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
