# Generated by Django 2.2 on 2019-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=120, null=True),
        ),
    ]
