# Generated by Django 2.2 on 2019-04-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190409_1551'),
        ('discussion', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Doctor'),
        ),
    ]
