# Generated by Django 2.2 on 2019-04-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_reply_on_answer_reply_on_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply_on_comment',
            old_name='answer',
            new_name='comment',
        ),
    ]
